# Generated by Django 2.0.1 on 2018-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Umec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(max_length=100, verbose_name='Igreja:')),
                ('initials', models.CharField(default='', max_length=10, verbose_name='Sigla')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Endereco:')),
            ],
            options={
                'verbose_name': 'UMEC',
                'verbose_name_plural': 'UMECs',
            },
        ),
    ]
