# Generated by Django 2.0.1 on 2018-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFemec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('office', models.CharField(choices=[('president', 'Presidente'), ('vice-president', 'Vice Presidente'), ('first-treasurer', '1 Tesoureiro(a)'), ('second-treasurer', '2 Tesoureiro(a)'), ('first-secretary', '1 Secretário(a)'), ('second-secretary', '2 Secretário(a)'), ('counselor', 'Conselheiro(a)')], max_length=20, verbose_name='Cargo')),
                ('date', models.DateField(help_text='Preencha no formato: dia/mês/ano. Ex: 24/07/1993', verbose_name='Data de Nascimento')),
                ('fone', models.CharField(default='', max_length=30, verbose_name='Telefone:')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Email:')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Endereco:')),
            ],
            options={
                'verbose_name_plural': 'Diretoria Femec',
                'verbose_name': 'Componente da diretoria',
            },
        ),
        migrations.CreateModel(
            name='BoardUmec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome:')),
                ('office', models.CharField(choices=[('president', 'Presidente'), ('vice-president', 'Vice Presidente'), ('first-treasurer', '1 Tesoureiro(a)'), ('second-treasurer', '2 Tesoureiro(a)'), ('first-secretary', '1 Secretário(a)'), ('second-secretary', '2 Secretário(a)'), ('counselor', 'Conselheiro(a)')], max_length=20, verbose_name='Cargo')),
                ('date', models.DateField(help_text='Preencha no formato: dia/mês/ano. Ex: 24/07/1993', verbose_name='Data de Nascimento')),
                ('fone', models.CharField(default='', max_length=30, verbose_name='Telefone:')),
                ('email', models.CharField(default='', max_length=30, verbose_name='Email:')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Endereco:')),
            ],
            options={
                'verbose_name_plural': 'Diretoria Umec',
                'verbose_name': 'Componente da diretoria',
            },
        ),
    ]
